sudo: false
language: c

before_install:
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin

install:
  - export PATH=/opt/ghc/7.10.2/bin:~/.local/bin:$PATH
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check --only-snapshot build

script:
  - export PATH=/opt/ghc/7.10.2/bin:~/.local/bin:$PATH
  - stack --no-terminal --skip-ghc-check build

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
      - libgmp-dev

cache:
  directories:
    - $HOME/.stack
