sudo: false
language: c

before_install:
  - wget -qO- https://get.haskellstack.org/ | sh
  
install:
  - stack --no-terminal update
  - stack --no-terminal setup

script:
  - stack --no-terminal build

cache:
  directories:
    - $HOME/.stack
